{% set name = "morningstar-data" %}
{% set version = "1.3.1" %}

package:
  name: morningstar-data
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morningstar_data-{{ version }}.tar.gz
  sha256: f4d7dd0a0ea960223f67614b14ef2e6faa5e3dd13fdd37959dfcc3ae50a79139

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pandas >=1.5.3
    - typeguard >=2.13.3
    - pyjwt >=2.4.0
    - boto3 >=1.20.1
    - cryptography 40.0.2
    - polling2 0.5.0
    - tenacity >=8.2.2
    - simplejson >=3.18.4
    - requests >=2.28.2
    - pyopenssl >=23.1.1
    - urllib3 >=1.26.0,<2.0.0

about:
  home: https://www.morningstar.com/products/md-python-package
  summary: Morningstar Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonzeper
    - mstar-ruifeng
    - chandr33
